build:
  image: dieunb/crb
  pull: true
  environment:
    RAILS_ENV: test
  commands:
    - rm -f config/database.yml
    - cp config/drone.database.yml config/database.yml
    - /bin/bash -l -c bundle install --without production
    - framgia-ci test-connect 127.0.0.1 3306
    - framgia-ci test-connect 127.0.0.1 6379
    - /bin/bash -l -c rake db:create db:migrate RAILS_ENV=test
    - framgia-ci run
compose:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: crb_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
  cache:
    image: redis

# build:
#   image: chikim/rails5_skeleton
#   environment:
#     REPO_URL: git@github.com:framgia/rails5_skeleton.git
#     EMAIL_USERNAME: sample@sample.com
#     EMAIL_PASSWORD: sample1
#     HOST: localhost:3000
#     AWS_REGION: ap-northeast-1
#     AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
#     S3_BUCKET_NAME: S3_BUCKET_NAME
#     DATABASE_HOSTNAME: 127.0.0.1
#     DATABASE_NAME: rails_app_development
#     DATABASE_USERNAME: test
#     DATABASE_PASSWORD: test
#     REDIS_HOSTNAME: localhost
#     RAILS_ENV: test
#     SECRET_KEY_BASE: ci_test
#     DEVISE_SECRET_KEY: ci_test
#     WEB_SERVER: unicorn
#     NUM_UNICORN_WORKERS: 3
#   commands:
#     - framgia-ci test-connect 127.0.0.1 3306
#     - bundle install
#     - RAILS_ENV=test rake db:create db:migrate
#     - framgia-ci run

# compose:
#   database:
#     image: mysql
#     environment:
#       MYSQL_DATABASE: rails_app_development
#       MYSQL_USER: test
#       MYSQL_PASSWORD: test
#       MYSQL_ROOT_PASSWORD: root
# cache:
#   mount:
#     - .git
