max_user_name_length: 40
max_email_length: 255
max_phone_length: 11
min_password_length: 6
max_password_length: 32
max_title_length: 100
max_tag_length: 15
default_per_page: 6
user_per_page: 8
no_avatar: "no-avatar.png"
hot_authors_amount: 3
post_per_page: 6
preview_content_length: 360
